//! Auto-generated image model registry from @earendil-works/pi-ai. DO NOT EDIT.
//!
//! Source: image-models.generated.js (35 image models, 1 provider)
//! Generated: 2026-07-09T19:35:02.371356+00:00

use crate::images::types::ImagesModel;
use crate::types::ModelCost;

/// Returns all built-in image models from the upstream pi-ai registry.
pub fn builtin_image_models() -> Vec<ImagesModel> {
    vec![
        ImagesModel {
            id: "black-forest-labs/flux.2-flex".into(),
            name: "Black Forest Labs: FLUX.2 Flex".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "black-forest-labs/flux.2-klein-4b".into(),
            name: "Black Forest Labs: FLUX.2 Klein 4B".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "black-forest-labs/flux.2-max".into(),
            name: "Black Forest Labs: FLUX.2 Max".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "black-forest-labs/flux.2-pro".into(),
            name: "Black Forest Labs: FLUX.2 Pro".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "bytedance-seed/seedream-4.5".into(),
            name: "ByteDance Seed: Seedream 4.5".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "google/gemini-2.5-flash-image".into(),
            name: "Google: Nano Banana (Gemini 2.5 Flash Image)".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 0.3_f64, output: 2.5_f64, cache_read: 0.03_f64, cache_write: 0.08333333333333334_f64 },
        },
        ImagesModel {
            id: "google/gemini-3-pro-image".into(),
            name: "Google: Nano Banana Pro (Gemini 3 Pro Image)".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 2_f64, output: 12_f64, cache_read: 0.19999999999999998_f64, cache_write: 0.375_f64 },
        },
        ImagesModel {
            id: "google/gemini-3-pro-image-preview".into(),
            name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 2_f64, output: 12_f64, cache_read: 0.19999999999999998_f64, cache_write: 0.375_f64 },
        },
        ImagesModel {
            id: "google/gemini-3.1-flash-image".into(),
            name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image)".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 0.5_f64, output: 3_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "google/gemini-3.1-flash-image-preview".into(),
            name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 0.5_f64, output: 3_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "google/gemini-3.1-flash-lite-image".into(),
            name: "Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 0.25_f64, output: 1.5_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "microsoft/mai-image-2.5".into(),
            name: "Microsoft: MAI-Image-2.5".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 5_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "openai/gpt-5-image".into(),
            name: "OpenAI: GPT-5 Image".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 10_f64, output: 10_f64, cache_read: 1.25_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "openai/gpt-5-image-mini".into(),
            name: "OpenAI: GPT-5 Image Mini".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 2.5_f64, output: 2_f64, cache_read: 0.25_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "openai/gpt-5.4-image-2".into(),
            name: "OpenAI: GPT-5.4 Image 2".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["image".into(), "text".into()],
            output: vec!["image".into(), "text".into()],
            cost: ModelCost { input: 8_f64, output: 15_f64, cache_read: 2_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "openai/gpt-image-1".into(),
            name: "OpenAI: GPT Image 1".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 10_f64, output: 10_f64, cache_read: 1.25_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "openai/gpt-image-1-mini".into(),
            name: "OpenAI: GPT Image 1 Mini".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 2.5_f64, output: 2.5_f64, cache_read: 0.25_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "openai/gpt-image-2".into(),
            name: "OpenAI: GPT Image 2".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 8_f64, output: 8_f64, cache_read: 2_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "openrouter/auto".into(),
            name: "Auto Router".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["text".into(), "image".into()],
            cost: ModelCost { input: -1000000_f64, output: -1000000_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v3".into(),
            name: "Recraft: Recraft V3".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4".into(),
            name: "Recraft: Recraft V4".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4-pro".into(),
            name: "Recraft: Recraft V4 Pro".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4-pro-vector".into(),
            name: "Recraft: Recraft V4 Pro Vector".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4-vector".into(),
            name: "Recraft: Recraft V4 Vector".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4.1".into(),
            name: "Recraft: Recraft V4.1".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4.1-pro".into(),
            name: "Recraft: Recraft V4.1 Pro".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4.1-pro-vector".into(),
            name: "Recraft: Recraft V4.1 Pro Vector".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4.1-utility".into(),
            name: "Recraft: Recraft V4.1 Utility".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4.1-utility-pro".into(),
            name: "Recraft: Recraft V4.1 Utility Pro".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "recraft/recraft-v4.1-vector".into(),
            name: "Recraft: Recraft V4.1 Vector".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "sourceful/riverflow-v2-fast".into(),
            name: "Sourceful: Riverflow V2 Fast".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "sourceful/riverflow-v2-pro".into(),
            name: "Sourceful: Riverflow V2 Pro".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "sourceful/riverflow-v2.5-fast".into(),
            name: "Sourceful: Riverflow V2.5 Fast".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "sourceful/riverflow-v2.5-pro".into(),
            name: "Sourceful: Riverflow V2.5 Pro".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
        ImagesModel {
            id: "x-ai/grok-imagine-image-quality".into(),
            name: "xAI: Grok Imagine Image Quality".into(),
            api: "openrouter-images".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into(), "image".into()],
            output: vec!["image".into()],
            cost: ModelCost { input: 0_f64, output: 0_f64, cache_read: 0_f64, cache_write: 0_f64 },
        },
    ]
}
