//! Auto-generated classifier model registry from @earendil-works/pi-ai. DO NOT EDIT.
//!
//! Source: signed schema-v6 provider shards (12 classifier models, 5 providers)
//! Generated: 2026-09-29T18:10:40.924Z

use crate::types::{ClassifierModel, ModelCost, ModelType};

/// Returns all built-in classifier models from the signed release registry.
pub fn builtin_classifier_models() -> Vec<ClassifierModel> {
    vec![
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "typesafe/jev".into(),
            name: "Jev".into(),
            api: "cloudflare-workers-ai-system-one".into(),
            provider: "cloudflare-workers-ai".into(),
            base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai"
                .into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 32000,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "jev-1.13".into(),
            name: "Jev 1.13".into(),
            api: "typesafe-system-one".into(),
            provider: "opencode".into(),
            base_url: "https://opencode.ai/zen/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0.042_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 32000,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "jev-1.13-free".into(),
            name: "Jev 1.13 Free".into(),
            api: "typesafe-system-one".into(),
            provider: "opencode".into(),
            base_url: "https://opencode.ai/zen/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 32000,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "jaredpalmer/kev-4b".into(),
            name: "Jared Palmer: Kev 4B".into(),
            api: "typesafe-system-one".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0.042_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 8192,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "respan/span-01".into(),
            name: "Respan: Span-01".into(),
            api: "typesafe-system-one".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0.02_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 4096,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "respan/span-01-lite".into(),
            name: "Respan: Span-01 Lite".into(),
            api: "typesafe-system-one".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 4096,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "respan/span-01-lite:free".into(),
            name: "Respan: Span-01 Lite (free)".into(),
            api: "typesafe-system-one".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 4096,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "typesafe/jev-1.13".into(),
            name: "TypeSafe: Jev 1.13".into(),
            api: "typesafe-system-one".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0.042_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 32000,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "upstage/solar-decide".into(),
            name: "Upstage: Solar Decide".into(),
            api: "typesafe-system-one".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0.05_f64,
                output: 0_f64,
                cache_read: 0.05_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 524288,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "~typesafe/jev-latest".into(),
            name: "TypeSafe: Jev Latest".into(),
            api: "typesafe-system-one".into(),
            provider: "openrouter".into(),
            base_url: "https://openrouter.ai/api/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0.042_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 32000,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "jev-latest".into(),
            name: "Jev".into(),
            api: "typesafe-system-one".into(),
            provider: "typesafe".into(),
            base_url: "https://api.typesafe.ai/v1/".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 64000,
            headers: None,
            api_key: None,
        },
        ClassifierModel {
            model_type: ModelType::Classifier,
            id: "typesafe-ai/jev".into(),
            name: "Jev".into(),
            api: "typesafe-system-one".into(),
            provider: "vercel-ai-gateway".into(),
            base_url: "https://ai-gateway.vercel.sh/typesafe/v1".into(),
            input: vec!["text".into()],
            input_limits: None,
            cost: ModelCost {
                input: 0.042_f64,
                output: 0_f64,
                cache_read: 0_f64,
                cache_write: 0_f64,
                tiers: vec![],
            },
            context_window: 32000,
            headers: None,
            api_key: None,
        },
    ]
}
